### ISSUE TITLE
AttributeError: module 'pymysql._auth' has no attribute 'scramble_old_password'

### ISSUE THREAD

**Issue by mangmang-zz** [PyMySQL/PyMySQL#1007] opened 2021-09-14 02:34 UTC
**Describe the bug**
When I connect to MySQL through pymysql.connect, an exception occurs. There are two questions to consult:

1. Why does the connection come to the judgment of code? The version of this database is 5.1.58. There is no exception when I connect to another MySQL database (version: 5.5.62).At the same time, Navicat can normally connect two databases。
2. Why_ There is no scramble under auth_ old_ password？

**Environment**
 - OS: linux
 - Server and version: MySQL 5.1.58
 - PyMySQL version: v1.0.2

**Comment by methane** [comment] 2021-09-14 02:35
Duplicate of #981

**Closed** 2021-09-14 02:36 UTC
