### ISSUE TITLE
struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by krypterro** [PyMySQL/PyMySQL#1010] opened 2021-10-04 14:47 UTC
Using sqlAlchemey with PyMySQL, db connection works fine, the app runs fine, but after the app has ran to completion with dozens of queries, inserts, and updates we close the DB connection and the application ends, then it throws a PyMYSQL Error:

**DB Setup Code:**
```
def __init__(self):
    set_data = {}
    set_data["db_ip"] = "127.0.0.1"
    set_data["db_name"] = "***db name***"
    set_data["db_user"] = "***db user***
    set_data["db_pass"] = "***db password**!"
    set_data["db_port"] = 3306
    engine_str = (
        "mysql+pymysql://"
        + set_data["db_user"]
        + ":"
        + set_data["db_pass"]
        + "@"
        + set_data["db_ip"]
        + ":" + str(set_data["db_port"])
        + "/"
        + set_data["db_name"]
        )

    engine = create_engine(
        engine_str,
        pool_size=10,
        max_overflow=20,
        pool_pre_ping=True,
        pool_recycle=1100
    )

    self.metadata = MetaData(bind=engine)
    self.session = scoped_session(sessionmaker(autocommit=False, autoflush=True, bind=engine))
    self.engine = engine
    conn = engine.connect()
    self.conn = conn
```

**DB Teardown Code:**
```
def session_scope_end(cbdb):
    logger.info("Closing Session Scope")
    try:
        yield cbdb.session
        cbdb.session.commit()
    except Exception as e:
        error = str(e)
        logger.warning(error)
        cbdb.session.rollback()
        raise
    finally:
        cbdb.session.close()
    cbdb.session.close()
    cbdb.engine.dispose()
    cbdb.conn.detach()
    cbdb.conn.close()
    return cbdb
```

**Environment**
OS: Ubuntu 20.04
Server version: 8.0.19 - MySQL Community Server - GPL
Protocol version: 10 
PyMySQL version:  1.0.2
Python: 3.8.5

**Error**
Exception during reset or similar

```
Traceback (most recent call last):
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/pymysql/connections.py", line 813, in _execute_command
    prelude = struct.pack("<iB", packet_size, command)
struct.error: required argument is not an integer
Exception closing connection <pymysql.connections.Connection object at 0x7f90f55cb250>
Traceback (most recent call last):
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/pymysql/connections.py", line 813, in _execute_command
    prelude = struct.pack("<iB", packet_size, command)
struct.error: required argument is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 247, in _close_connection
    self._dialect.do_close(connection)
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 673, in do_close
    dbapi_connection.close()
  File "/home/krypterro/PyApps/devbot/.venv/lib/python3.8/site-packages/pymysql/connections.py", line 408, in close
    send_data = struct.pack("<iB", 1, COMMAND.COM_QUIT)
struct.error: required argument is not an integer
```

**Comment by methane** [comment] 2021-10-05 08:59
Please provide a "reproducible" example.

**Comment by davidlampach** [comment] 2022-10-04 16:21
Did this never get resolved?  I am getting this exact error

**Comment by methane** [comment] 2022-10-05 04:05
This won't resolved forever unless someone provide a complete step to reproduce.

**Comment by ruegi** [comment] 2023-01-27 20:27
Hi,
Today I just stumbled about the same error.
It only appears, when I use 'mysql+pymysql' in the connect string. 
Without 'pymysql', the program terminates well, but gets encoding errors.
So I need 'pymysql'.
But then, the following error occurs in closing then connection:
```
Exception closing connection <pymysql.connections.Connection object at 0x00000132962AD8D0>
Traceback (most recent call last):
  File "C:\Users\rg\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\rg\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\rg\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
  File "C:\Users\rg\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 480, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "C:\Users\rg\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 813, in _execute_command
    prelude = struct.pack("<iB", packet_size, command)
struct.error: required argument is not an integer
```
Editing the 'connections.py' file lead to the function 'close'.  
There I added a simple print statement:
```
line 408: print("===>", COMMAND.COM_QUIT)
line 409:  send_data = struct.pack("<iB", 1, COMMAND.COM_QUIT)
```
The result was: `===> None`

Maybe this might help to trace the error. Why is the constant 'COMMAND.COM_QUIT' None?

Any help would be appreciated.
Ruegi

**Comment by methane** [comment] 2023-01-31 05:27
> Maybe this might help to trace the error. Why is the constant 'COMMAND.COM_QUIT' None?

Maybe because you are shutting down the interpreter.
You must close connections, before exit your program.

**Comment by methane** [comment] 2023-01-31 05:28
I can not support PyMySQL works perfectly during interpreter shutdown. No plan to fix this.

**Closed by methane** 2023-01-31 05:28 UTC

**Comment by ruegi** [comment] 2023-02-04 19:25
Thank you for your comment.
After reorganizing my code, the error disappeard.
Explanation:
In my old db module, i instatiated _engine_, _connection_ and _session_ globaly.
The single functions then used these global vars to query and update the db.
That lead to the mentioned errors.

In my new module, I am only instantiating _engine_ and _sessionmaker_ globaly.
In the functions in my db module, I am only using ORM access to the db.
The necessary _session_ is opened and closed locally in a structure like:
```
with Session(bind=engine) as session:
        try:
            q = session.query(dbtable)
             ...
        except SQLAlchemyError as e:
            error = str(e.orig)
            # error Message 

```

This construction did the trick.
Sadly, I can't repoduce the error with a simplified code.
Thanks again
