### ISSUE TITLE
pymysql doesn't support --protocol={TCP|SOCKET|PIPE|MEMORY}

### ISSUE THREAD

**Issue by BuhtigithuB** [PyMySQL/PyMySQL#1021] opened 2022-01-26 17:15 UTC
**Describe the bug**
pymysql doesn't support --protocol={TCP|SOCKET|PIPE|MEMORY}

**To Reproduce**
Try to connect to instance of MySQL Official container image running container without --protocol=TCP if you can't connect to database as it is not accessible through unix socket but only with --protocol=TCP

**Expected behavior**
Add support for --protocol to be passed as parameter for Connection class

Ref.: https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/connections.py#L167

**Environment**
 - OS: Linux (ubuntu 18.04)
 - Server and version: MySQL 8.0.28 official container image (https://hub.docker.com/_/mysql)
 - PyMySQL version: 0.9.3

**Additional context**
I started implement "protocol" to be passed in ansible.community.mysql (https://github.com/ansible-collections/community.mysql/pull/280), but realize it won't work.

**Comment by BuhtigithuB** [comment] 2022-02-01 21:22
UP

**Comment by methane** [comment] 2022-02-01 23:55
* PyMySQL never use unix socket unless `unix_socket=True` is passed.
* We need to add it to mysqlclient too. It uses unix socket when host is "localhost", like all other official mysql client.
* But please don't hurry/PING me. There is well known and old workaround; use "127.0.0.1" instead of "localhost". Every MySQL experts knows this, because this is very famous MySQL pitfall.

**Comment by methane** [comment] 2023-05-23 09:08
I decided to "won't fix"

* First of all, this is a library. Not commandline tool. `--protocol=` doesn't make sense at all.
* Both of mysqlclient and MySQL Connector/Python doesn't provide such an option.
* As I wrote above, we already have `unix_socket` option. Untill we support PIPE or MEMORY, this option is 100% duplicate of `unix_socket` option.
* Someone added "vote down" reaction to my explanation. It hurt my motivation.

**Closed by methane** 2023-05-23 09:08 UTC
