### ISSUE TITLE
function `_auth.scramble_old_password` lost

### ISSUE THREAD

**Issue by fhkankan** [PyMySQL/PyMySQL#1006] opened 2021-09-06 03:18 UTC
**Describe the bug**
version 1.0.2
connections.py line 924/996 need `_auth.scramble_old_password`, but _auth.py does not have the function

Code:

```py
 data = _auth.scramble_old_password(self.password, self.salt) + b"\0"
  

elif plugin_name == b"mysql_old_password":
            data = (
                _auth.scramble_old_password(self.password, auth_packet.read_all())
                + b"\0"
            )

```

**Environment**
 - PyMySQL version: 1.0.2

**Comment by methane** [comment] 2021-09-07 07:05
Thank you for reporting. But this is a duplicate of #981 and fixed in #1003 already.

**Closed by methane** 2021-09-07 07:05 UTC
