### ISSUE TITLE
FAIL: test_issue_15 (pymysql.tests.test_issues.TestOldIssues)

### ISSUE THREAD

**Issue by brunoqc** [PyMySQL/PyMySQL#194] opened 2013-11-11 14:19 UTC
mysql 5.1.70
pymysql b4284c980c1e561b2ca9966d30869fa0f545e772
Windows 7 (64-bit)

```python
C:\Users\bbigras\dev\PyMySQL>runtests.py pymysql.tests.test_issues.TestOldIssues
.F.s......
======================================================================
FAIL: test_issue_15 (pymysql.tests.test_issues.TestOldIssues)
query should be expanded before perform character encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bbigras\dev\PyMySQL\pymysql\tests\test_issues.py", line 115, in test_issue_15
    self.assertEqual(u'\xe4\xf6\xfc', c.fetchone()[0])
AssertionError: u'\xe4\xf6\xfc' != u''
- \xe4\xf6\xfc
+


----------------------------------------------------------------------
Ran 10 tests in 5.300s

FAILED (failures=1, skipped=1)
No garbages!
```

**Comment by methane** [comment] 2015-02-01 02:24
How did you setup?  Could you try this?

```
show create database test_pymyql;
```

**Comment by brunoqc** [comment] 2015-02-02 19:30
I don't have this same `test_pymyql` database anymore and I also run MySQL 5.5.41 now.

Do you want me to test b4284c9 or the latest version with a new `test_pymyql` database?

**Comment by methane** [comment] 2015-02-02 19:57
I wonder if your database was not utf-8.
Tests may fail on misconfigured databases, and it's not a bug.
So I need to know how did you setup your database.

**Comment by methane** [comment] 2015-02-03 20:41
I close this issue since I can't know necessary information anymore.
I'm sorry about late response.

**Closed by methane** 2015-02-03 20:41 UTC
