### ISSUE TITLE
SHA256 user account issue

### ISSUE THREAD

**Issue by jmcgrath207** [PyMySQL/PyMySQL#532] opened 2016-11-26 22:40 UTC
Issue with user account that uses SHA256 Password.

I was trying to connect to mysql 5.7.16 docker container with a user account I created with a SHA256 password and I am getting this error.

```
  File "/usr/local/lib/python3.5/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 906, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 1123, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 1185, in _process_auth
    raise err.OperationalError(2059, "Authentication plugin '%s' not configured" % plugin_name)
pymysql.err.OperationalError: (2059, "Authentication plugin 'b'sha256_password'' not configured")

Process finished with exit code 1
```

Starting at line 1147 it appears this is where the decision is made based on the authentication types but I don't see any that mention SHA256

## Executable script to reproduce (for bugs)

```
#Open database connection
db = pymysql.connect("mysql","admin","password")
#prepare a cursor object using cursor() method
cursor = db.cursor()
```

## Your Environment

* Operating System and version:
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

Linux 701fd9099c55 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 GNU/Linux

mysql 5.7.16 docker container

* PyMySQL Version used:

PyMySQL==0.7.9

**Comment by methane** [comment] 2016-11-27 07:18
No plan to support sha256 password plugin.
Contribution is welcome.

**Comment by lishuode** [comment] 2017-06-23 06:50
#583

**Comment by lishuode** [comment] 2017-06-23 06:51
@sonance207 I'm adding code for SHA256 now. #583 SHA256 plugin support.

**Comment by sonance207** [comment] 2017-06-28 03:46
The issue is being resolved in #583. Closing case

**Comment by sharma-dhrv** [comment] 2018-03-04 10:45
Apparently Issue #583 was closed without a merge thereby not adding support for `sha256_password` plugin. No specific reason or action was stated at the end of issue. This issue seemed to have been closed prematurely in anticipation that the said PR will be accepted and merged.

I believe MySQL supports a exchange of public RSA key for the client to encrypt the password for the exchange in case unencrypted connection is used. I understand that it would be appropriate for user to use TLS connection over simple RSA encryption but is there any other reason for not having the feature offered by #583?

**Comment by methane** [comment] 2018-03-05 00:19
I don't want add dependency (for RAS) in minor release.
And I should make some design decision about the pull request (e.g. adding cryptography as hard dependency or optional dependency), but I'm very busy last year.

That was reason I couldn't merge it soon.  And the PR author closed before I have free time.

**Closed** 2018-06-27 10:12 UTC
