### ISSUE TITLE
Attribute error connections.py trying to use an inexisting method

### ISSUE THREAD

**Issue by DiegoMagg** [PyMySQL/PyMySQL#1000] opened 2021-08-27 12:10 UTC
**Import error**
cannot import name 'scramble_old_password' from 'pymysql._auth'

**To Reproduce**
```
from pymysql import _auth
_auth.scramble_old_password()
```
Hi, I had a problem with pymysql generating an attribute error in a service running on docker. Looking at the code I noticed that there is a call to a method that doesn't exist in the "_auth" file.

```
        elif plugin_name == b"mysql_old_password":
            data = (
                _auth.scramble_old_password(self.password, auth_packet.read_all())
                + b"\0"
            )
```

https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/connections.py line 966.

`scramble_old_password` doesn't exist on _auth file anymore.

**Comment by methane** [comment] 2021-08-28 01:11
Thank you for reporting. But this is duplicate of #981.

**Closed by methane** 2021-08-28 01:11 UTC
