### ISSUE TITLE
Password cannot contain special characters

### ISSUE THREAD

**Issue by cecyLDY** [PyMySQL/PyMySQL#1041] opened 2022-03-29 01:56 UTC
PyMySQL           0.10.1
mysql                 5.5
password           A]9bd.@FbT#[55Aj
 pymysql.connect( host='ip',port=3306, user='root',  passwd='A]9bd.@FbT#[55Aj',  db='', use_unicode=True,charset="utf8",autocommit=True,connect_timeout=1)

error:u"Access denied for user 'root'...

But there is no problem with linking mysql directly with that password.

Dose anyone has an solution/suggestion?

Thinks!

**Comment by methane** [comment] 2022-03-29 02:05
> But there is no problem with linking mysql directly with that password.

Elaborate?

**Comment by cecyLDY** [comment] 2022-03-30 06:24
> 

It means that the database password is OK, and now pymysql.connect cannot link.
I tried to use url to transcode the password but still can't connect.
Is there any way to fix it?

**Comment by cecyLDY** [comment] 2022-03-30 06:26
@methane 
It means that the database password is OK, and now pymysql.connect cannot link.
I tried to use url to transcode the password but still can't connect.
Is there any way to fix it?

**Comment by methane** [comment] 2022-03-30 06:28
> It means that the database password is OK,

It's not describe anything. What is OK?
Write down what you did exactly.

**Comment by cecyLDY** [comment] 2022-03-30 06:30
Failed to connect using password containing special characters

**Comment by methane** [comment] 2022-03-30 06:33
If you succeed to use the password with the mysql CLI with -p option, you need to write the full command line.
If you used my.cnf file, you need to write the my.cnf file too.

This is minimal requirement for asking technical questions.

**Comment by cecyLDY** [comment] 2022-03-30 06:35
pymysql.connect( host='ip',port=3306, user='root', passwd='A]9bd.@fbt#[55Aj', db='', use_unicode=True,charset="utf8",autocommit=True,connect_timeout=1)


I can't connect to mysql using pymysql because the password contains special characters, do you understand?

**Comment by methane** [comment] 2022-03-30 06:51
What did you do **exactly** when you can use that password???

**Comment by cecyLDY** [comment] 2022-03-30 07:30
My God, this password: A]9bd.@fbt#[55Aj, you can connect to the database directly using the mysql command line, but using pymysql.connect will give an error, should I be clear?

**Comment by methane** [comment] 2022-03-30 07:52
No. Have you read my comment? I said:

> If you succeed to use the password with the mysql CLI with -p option, you need to write the full command line.
> If you used my.cnf file, you need to write the my.cnf file too.

You didn't write actual command line. It is not elaborate.

**Comment by methane** [comment] 2022-03-30 08:05
Additionally, please use Markdown syntax, like `A]9bd.@fbt#[55Aj`.
You are sending unnecessary PING to other GitHub user.

**Comment by cecyLDY** [comment] 2022-03-30 09:23
You are so hard to communicate, funny

**Comment by methane** [comment] 2022-03-30 09:26
I close this because reporter doesn't provide step to reproduce so I can not reproduce it.

**Closed** 2022-03-30 09:26 UTC

**Comment by methane** [comment] 2022-03-31 05:00
For the record, PyMySQL **can** use password like `A]9bd.@fbt#[55Aj`.
So this issue was likely author's mistake. For example, `mysql -uroot -pA]9bd.@fbt#[55Aj`. But I am not sure. I need the actual commandline to confirm it.

I repeatedly asked the author to actual commandline. But the author didn't.
He said "You are so hard to communicate, funny".
This is very impoliteness and no respect.

This types of issue report is like DoS attack to OSS maintainers. I am angry about issues like this and tired to receive notify from issue trackers.

**Please provide concrete steps to reproduce!!**
**Please provide concrete steps to reproduce!!**
**Please provide concrete steps to reproduce!!**
